
'use server';

/**
 * @fileOverview A flow that continues a story chain.
 * - continueStoryChain - A function that adds the next sentence to a story.
 */

import {ai} from '@/ai/genkit';
import { z } from 'zod';

const ContinueStoryChainInputSchema = z.object({
  story: z.string().describe('The existing story so far.'),
  genre: z.string().describe('The genre of the story.'),
});
export type ContinueStoryChainInput = z.infer<typeof ContinueStoryChainInputSchema>;

const ContinueStoryChainOutputSchema = z.object({
  nextSentence: z.string().describe('The next sentence in the story, generated by the AI.'),
});
export type ContinueStoryChainOutput = z.infer<typeof ContinueStoryChainOutputSchema>;


const prompt = ai.definePrompt({
  name: 'continueStoryChainPrompt',
  input: {schema: ContinueStoryChainInputSchema},
  output: {schema: ContinueStoryChainOutputSchema},
  prompt: `You are a collaborative storyteller. You are participating in a story chain game.
  The genre is: {{genre}}.
  The story so far is:
  "{{story}}"
  
  Your task is to add the very next sentence to continue the story in a logical and creative way. 
  Keep your sentence concise. Do not add more than one sentence.
  `,
});

const continueStoryChainFlow = ai.defineFlow(
  {
    name: 'continueStoryChainFlow',
    inputSchema: ContinueStoryChainInputSchema,
    outputSchema: ContinueStoryChainOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

export async function continueStoryChain(
  input: ContinueStoryChainInput
): Promise<ContinueStoryChainOutput> {
  return continueStoryChainFlow(input);
}
