
import type { Game } from "@/lib/types";
import {
  Swords, Crosshair, Flame, Activity, Castle, Hexagon,
  Puzzle,
  SpellCheck,
  Mic,
  BookText,
  MessageSquareQuote,
  Ear,
  Palette,
  Clapperboard,
  Gavel,
  BookCopy,
  HelpCircle,
  Ban,
  Search,
  Disc,
  Globe,
  Skull,
  Star,
  ListChecks,
  Gift,
  Link,
  BookOpenCheck,
  Compass,
  Flashlight,
  Construction,
  LayoutGrid,
  Copy,
  Target,
  Smile,
  Fingerprint,
  Zap,
  Orbit,
  FlaskConical,
  Shapes,
  Calculator,
  Atom,
  PieChart,
  Rocket,
  ScrollText,
  Thermometer,
  MessageSquare,
  Heart,
  Clock,
  Sparkles,
  CloudRain,
  Plane,
  Binary,
  Dna,
  Building2,
  Grid3X3,
  Newspaper,
  Rotate3d,
} from "lucide-react";

export const allGames: Game[] = [
  {
    title: "Arithmetic Ace",
    slug: "arithmetic-ace",
    description: "Solve rapid-fire mental math problems to climb the global leaderboard.",
    level: "intermediate",
    focus: "grammar",
    subject: "math",
    icon: Calculator,
  },
  {
    title: "Fraction Fusion",
    slug: "fraction-fusion",
    description: "Match visual models to their numeric fractions in this high-speed challenge.",
    level: "beginner",
    focus: "geometry",
    subject: "math",
    icon: PieChart,
  },
  {
    title: "Math Mission: Situations",
    slug: "math-mission-situations",
    description: "Analyze complex word problems and use the digital canvas to sketch your solution within the time limit.",
    level: "intermediate",
    focus: "reading",
    subject: "math",
    icon: ScrollText,
  },
  {
    title: "Time Traveler",
    slug: "time-traveler",
    description: "Master elapsed time and scheduling by calculating durations in situational scenarios.",
    level: "intermediate",
    focus: "reading",
    subject: "math",
    icon: Clock,
  },
  {
    title: "Probability Pilot",
    slug: "probability-pilot",
    description: "Navigate flight routes by calculating the odds of atmospheric success.",
    level: "intermediate",
    focus: "reading",
    subject: "math",
    icon: Plane,
  },
  {
    title: "Element Escapade",
    slug: "element-escapade",
    description: "Identify elements of the periodic table by their atomic signatures.",
    level: "advanced",
    focus: "vocabulary",
    subject: "science",
    icon: Atom,
  },
  {
    title: "Solar System Scout",
    slug: "solar-system-scout",
    description: "Identify planets and celestial bodies based on their unique atmospheric and physical properties.",
    level: "intermediate",
    focus: "biology",
    subject: "science",
    icon: Rocket,
  },
  {
    title: "States of Matter Master",
    slug: "states-of-matter",
    description: "Identify substances and their properties across Solids, Liquids, Gases, and Plasma.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "science",
    icon: Thermometer,
  },
  {
    title: "Anatomy Academy",
    slug: "anatomy-academy",
    description: "Identify human organs and body systems based on their vital biological roles.",
    level: "intermediate",
    focus: "biology",
    subject: "science",
    icon: Heart,
  },
  {
    title: "Atmospheric Ace",
    slug: "atmospheric-ace",
    description: "Identify layers of the atmosphere and weather phenomena using satellite sensor data.",
    level: "intermediate",
    focus: "biology",
    subject: "science",
    icon: CloudRain,
  },
  {
    title: "3D Lexi-Sphere",
    slug: "lexi-sphere",
    description: "Navigate a rotating 3D cloud of words to find the one that matches the definition.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Orbit,
  },
  {
    title: "Cellular Explorer 3D",
    slug: "cellular-explorer-3d",
    description: "Spin the 3D cell structure to identify organelles based on their biological functions.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "science",
    icon: FlaskConical,
  },
  {
    title: "Geometry Galaxy 3D",
    slug: "geometry-galaxy-3d",
    description: "Navigate space to identify 3D shapes like Prisms, Pyramids, and Polyhedrons.",
    level: "intermediate",
    focus: "geometry",
    subject: "math",
    icon: Shapes,
  },
  {
    title: "Dialogue Dojo",
    slug: "dialogue-dojo",
    description: "Navigate real-world social scenarios. Choose the most natural and polite responses to master conversational English.",
    level: "intermediate",
    focus: "conversation",
    subject: "english",
    icon: MessageSquare,
  },
  {
    title: "Riddle Realm",
    slug: "riddle-realm",
    description: "Consult the AI Oracle to solve mystical linguistic puzzles and wordplay.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Sparkles,
  },
  {
    title: "Article Architect",
    slug: "article-architect",
    description: "Choose the correct article (a, an, the, or no article) to complete the sentence.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Construction,
  },
  {
    title: "Auction Action",
    slug: "auction-action",
    description: "Is the sentence correct? Bet on your grammar knowledge to win!",
    level: "advanced",
    focus: "grammar",
    subject: "english",
    icon: Gavel,
  },
  {
    title: "Bingo Boost",
    slug: "bingo-boost",
    description: "Listen to definitions and mark the right words on your bingo card.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: Star,
  },
  {
    title: "Charades Challenge",
    slug: "charades-challenge",
    description: "Act out the prompt for your friends to guess.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: Clapperboard,
  },
  {
    title: "Choose Your Gift",
    slug: "choose-your-gift",
    description: "Choose a gift to reveal a sentence and points. One is good, one is bad!",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Gift,
  },
  {
    title: "Context Detective",
    slug: "context-detective",
    description: "Use context clues to guess the missing word in a short story.",
    level: "intermediate",
    focus: "reading",
    subject: "english",
    icon: Fingerprint,
  },
  {
    title: "Crossword Connect",
    slug: "crossword-connect",
    description: "Solve the clues to complete the crossword puzzle.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Puzzle,
  },
  {
    title: "Emoji Enigma",
    slug: "emoji-enigma",
    description: "Translate the AI's emoji sequence into English words or phrases!",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Smile,
  },
  {
    title: "Grammar Guru",
    slug: "grammar-guru",
    description: "Fix the sentences and become a grammar master.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: BookText,
  },
  {
    title: "Hangman Challenge",
    slug: "hangman-challenge",
    description: "Guess the secret word letter by letter before you run out of chances.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: Skull,
  },
  {
    title: "Idiom Illumination",
    slug: "idiom-illumination",
    description: "Learn and use common English idioms in context.",
    level: "advanced",
    focus: "vocabulary",
    subject: "english",
    icon: MessageSquareQuote,
  },
  {
    title: "Jeopardy Classroom",
    slug: "jeopardy-classroom",
    description: "Compete in teams to answer questions in various categories and point values.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: LayoutGrid,
  },
  {
    title: "Listening Labyrinth",
    slug: "listening-labyrinth",
    description: "Navigate a maze by following spoken directions.",
    level: "intermediate",
    focus: "pronunciation",
    subject: "english",
    icon: Ear,
  },
  {
    title: "Mystery Box",
    slug: "mystery-box",
    description: "Answer questions correctly to open a mystery box. Will you keep the points, or give them away?",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Gift,
  },
  {
    title: "Odd One Out",
    slug: "odd-one-out",
    description: "Find the word or phrase that doesn't belong with the others!",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Target,
  },
  {
    title: "Phonics Flash",
    slug: "phonics-flash",
    description: "Guess the hidden word based on the phonics sound before time runs out.",
    level: "intermediate",
    focus: "pronunciation",
    subject: "english",
    icon: Flashlight,
  },
  {
    title: "Pictionary Party",
    slug: "pictionary-party",
    description: "Draw the word prompt and let your friends guess!",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Palette,
  },
  {
    title: "Pronunciation Pro",
    slug: "pronunciation-pro",
    description: "Listen and repeat phrases to perfect your accent.",
    level: "advanced",
    focus: "pronunciation",
    subject: "english",
    icon: Mic,
  },
  {
    title: "Reading Comprehension",
    slug: "reading-comprehension",
    description: "Read a passage and answer questions to test your understanding.",
    level: "intermediate",
    focus: "reading",
    subject: "english",
    icon: BookOpenCheck,
  },
  {
    title: "Running Dictation",
    slug: "running-dictation",
    description: "Memorize and write down sentences in a fast-paced challenge.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: BookCopy,
  },
  {
    title: "Sentence Scramble",
    slug: "sentence-scramble",
    description: "Unscramble the words to form correct sentences.",
    level: "beginner",
    focus: "grammar",
    subject: "english",
    icon: Puzzle,
  },
  {
    title: "Spelling Bee",
    slug: "spelling-bee",
    description: "A classic competition for practicing vocabulary words.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: SpellCheck,
  },
  {
    title: "Spin the Wheel",
    slug: "spin-the-wheel",
    description: "Spin, choose a color, and answer a question to score points for your team.",
    level: "beginner",
    focus: "grammar",
    subject: "english",
    icon: Disc,
  },
  {
    title: "Story Chain",
    slug: "story-chain",
    description: "Collaborate with friends and AI to build an exciting story, one sentence at a time.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Link,
  },
  {
    title: "Synonym Sleuth",
    slug: "synonym-sleuth",
    description: "Find the correct synonym for the given word from multiple choices.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Search,
  },
  {
    title: "Taboo Tussle",
    slug: "taboo-tussle",
    description: "Describe a word without using the forbidden 'taboo' words.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Ban,
  },
  {
    title: "Top 5 Quiz",
    slug: "top-5-quiz",
    description: "Create and play a customizable top 5 list quiz.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: ListChecks,
  },
  {
    title: "Twenty Questions",
    slug: "twenty-questions",
    description: "Guess the secret object by asking up to 20 yes/no questions.",
    level: "beginner",
    focus: "grammar",
    subject: "english",
    icon: HelpCircle,
  },
  {
    title: "Vocab Voyage",
    slug: "vocab-voyage",
    description: "Match words to their definitions in a race against time.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: SpellCheck,
  },
  {
    title: "Vocabulary Match-Up",
    slug: "vocabulary-match-up",
    description: "Flip cards and find the matching pairs of words and definitions.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: Copy,
  },
  {
    title: "Wheel of Fortune",
    slug: "wheel-of-fortune",
    description: "Spin the wheel and complete a sentence like, 'I will [verb from wheel]'.",
    level: "beginner",
    focus: "grammar",
    subject: "english",
    icon: Disc,
  },
  {
    title: "Word Morph",
    slug: "word-morph",
    description: "Transform words by adding prefixes or suffixes to match a definition.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Zap,
  },
  {
    title: "World Tour Wheel",
    slug: "world-tour-wheel",
    description: "Spin the wheel to learn countries and their nationalities.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Globe,
  },
  {
    title: "Algebraic Abyss",
    slug: "algebraic-abyss",
    description: "Navigate a cosmic 3D tunnel and solve equations before they consume you.",
    level: "advanced",
    focus: "geometry",
    subject: "math",
    icon: Binary,
  },
  {
    title: "Evolution Expedition",
    slug: "evolution-expedition",
    description: "Guide your organism through millions of years of adaptation in a dynamic morphing world.",
    level: "intermediate",
    focus: "biology",
    subject: "science",
    icon: Dna,
  },
  {
    title: "Syntax Skyline",
    slug: "syntax-skyline",
    description: "Construct complex sentences to build a glowing neon city in this linguistic skyscraper challenge.",
    level: "advanced",
    focus: "grammar",
    subject: "english",
    icon: Building2,
  },
  {
    title: "Math Matrix",
    slug: "math-matrix",
    description: "Crack the code by analyzing 2x2 data grids and deducing the mathematical sequence in this cyberpunk challenge.",
    level: "advanced",
    focus: "geometry",
    subject: "math",
    icon: Grid3X3,
  },
  {
    title: "Vocab Vortex",
    slug: "vocab-vortex",
    description: "Match complex words to their true synonyms before they are consumed by the synaptic black hole.",
    level: "advanced",
    focus: "vocabulary",
    subject: "english",
    icon: Orbit,
  },
  {
    title: "Quantum Quest",
    slug: "quantum-quest",
    description: "Contain destabilizing isotopes by rapidly pairing their chemical symbols to their elemental names.",
    level: "advanced",
    focus: "vocabulary",
    subject: "science",
    icon: Atom,
  },
  {
    title: "Grammar Gladiator",
    slug: "grammar-gladiator",
    description: "Slay grammatical errors in the colosseum to claim eternal glory.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Swords,
  },
  {
    title: "Synonym Sniper",
    slug: "synonym-sniper",
    description: "Lock on target and snipe the correct synonym before it escapes your scope.",
    level: "advanced",
    focus: "vocabulary",
    subject: "english",
    icon: Crosshair,
  },
  {
    title: "Idiom Inferno",
    slug: "idiom-inferno",
    description: "Guess the correct meaning of idioms before the lava swallows you whole.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Flame,
  },
  {
    title: "Molecule Maker",
    slug: "molecule-maker",
    description: "Initiate the synthesizer and select the correct molecular formula for the given compound.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "science",
    icon: FlaskConical,
  },
  {
    title: "Bio Hazard",
    slug: "bio-hazard",
    description: "Identify biological components correctly to neutralize pathogens before they mutate.",
    level: "advanced",
    focus: "biology",
    subject: "science",
    icon: Activity,
  },
  {
    title: "Newton's Nightmare",
    slug: "newtons-nightmare",
    description: "Solve basic physics calculations to maneuver the satellite out of danger.",
    level: "advanced",
    focus: "grammar",
    subject: "science",
    icon: Rocket,
  },
  {
    title: "Fraction Fortress",
    slug: "fraction-fortress",
    description: "Match the equivalent fraction to load the catapults and repel the invaders.",
    level: "intermediate",
    focus: "geometry",
    subject: "math",
    icon: Castle,
  },
  {
    title: "Data Detective",
    slug: "data-detective",
    description: "Analyze the evidence to calculate the Mean, Median, Mode, or Range and uncover the truth.",
    level: "advanced",
    focus: "geometry",
    subject: "math",
    icon: Search,
  },
  {
    title: "Geometry Genius",
    slug: "geometry-genius",
    description: "Calculate the properties of ancient geometric structures to discover hidden artifacts.",
    level: "intermediate",
    focus: "geometry",
    subject: "math",
    icon: Hexagon,
  },
  {
    title: "Neon Numbers Labyrinth",
    slug: "neon-numbers-labyrinth",
    description: "Navigate a retro-futuristic grid by solving complex arithmetic sequences.",
    level: "intermediate",
    focus: "geometry",
    subject: "math",
    icon: Binary,
  },
  {
    title: "Galactic Cell Defender",
    slug: "galactic-cell-defender",
    description: "Defend your cellular core from viruses by answering biology and chemistry trivia.",
    level: "advanced",
    focus: "biology",
    subject: "science",
    icon: Dna,
  },
  {
    title: "Mystic Synonym Spire",
    slug: "mystic-synonym-spire",
    description: "Build a magical bridge by matching synonyms and antonyms to climb the spire.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Castle,
  },
  {
    title: "Coordinate Cosmos",
    slug: "coordinate-cosmos",
    description: "Navigate through space coordinates by identifying quadrants, reflecting points, and calculating distances.",
    level: "intermediate",
    focus: "geometry",
    subject: "math",
    icon: Orbit,
  },
  {
    title: "Gene Genius",
    slug: "gene-genius",
    description: "Predict the offspring's genetic outcomes using Punnett squares in a modern lab simulator.",
    level: "intermediate",
    focus: "biology",
    subject: "science",
    icon: Dna,
  },
  {
    title: "Literary Device Legend",
    slug: "literary-device-legend",
    description: "Identify similes, metaphors, hyperboles, and other literary devices in an epic arcade language duel.",
    level: "intermediate",
    focus: "reading",
    subject: "english",
    icon: BookText,
  },
  {
    title: "The Daily Verse",
    slug: "daily-verse",
    description: "Read simplified daily news and test your comprehension in this AI-powered aggregator game.",
    level: "intermediate",
    focus: "reading",
    subject: "english",
    icon: Newspaper,
  },
  {
    title: "Cosmic Word Voyager",
    slug: "cosmic-word-voyager",
    description: "Pilot your spacecraft through hypergates by solving language mysteries. Fuel the ship with vocabulary, shield your hull from errors!",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Rocket,
  },
  {
    title: "Spellcaster Spell-Defense",
    slug: "spellcaster-defense",
    description: "Unleash grammar incantations to defend the ancient wizard spire from falling spelling phantoms.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Flame,
  },
  {
    title: "3D Exploration & Questing",
    slug: "exploration-quest-3d",
    description: "Explore beautifully rendered 3D environments (like a kitchen or city) and interact with objects to learn their names.",
    level: "intermediate",
    focus: "vocabulary",
    subject: "english",
    icon: Globe,
  },
  {
    title: "Animated \"Living\" Puzzles",
    slug: "living-puzzles-3d",
    description: "Assemble interactive 3D word puzzles and watch them come to life with living animations once completed.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: Puzzle,
  },
  {
    title: "Interactive Character Conversations",
    slug: "character-conversations-3d",
    description: "Engage in social conversations with fully animated 3D characters to learn pronunciation and gestures.",
    level: "intermediate",
    focus: "conversation",
    subject: "english",
    icon: Smile,
  },
  {
    title: "AI Choose-Your-Own",
    slug: "ai-storyteller-adventure",
    description: "Navigate a continuous procedural story by unlocking action branches with grammar and spelling challenges.",
    level: "intermediate",
    focus: "grammar",
    subject: "english",
    icon: Compass,
  },
  {
    title: "3D Vocab Flipper",
    slug: "vocab-flipper-3d",
    description: "Flip beautiful 3D flashcards to match words with their definition and build your vocabulary.",
    level: "beginner",
    focus: "vocabulary",
    subject: "english",
    icon: Rotate3d,
  },
  {
    title: "3D Math Vault",
    slug: "math-vault-3d",
    description: "Solve math equations to decrypt the security vault and swing open the 3D doors to reveal the core.",
    level: "intermediate",
    focus: "geometry",
    subject: "math",
    icon: Rotate3d,
  },
];

export const getGameBySlug = (slug: string) => {
    return allGames.find((g) => g.slug === slug);
}
